-- Account: zevronblades
-- Character: zevron
-- Generated on: Sat Sep  9 13:59:10 2023
characterData = {
	firstName = "Zevron",
	lastName = "Blades",
	cash = 60589,
	bank = 0,
	experience = 38683,
	corruption = 0,
	faction = "empire",
	factionRank = "11",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 0,
	lightsaberBuilder = -1,
	skills = {
		"rp_precision_novice",
		"species_human",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_charisma_a01",
		"rp_precision_a01",
		"rp_awareness_a01",
		"rp_intelligence_a01",
		"rp_constitution_a01",
		"rp_awareness_a02",
		"rp_charisma_a02",
		"rp_intelligence_a02",
		"rp_precision_a02",
		"rp_constitution_a02",
		"rp_awareness_a03",
		"rp_charisma_a03",
		"rp_constitution_a03",
		"rp_intelligence_a03",
		"rp_precision_a03",
		"rp_awareness_a04",
		"rp_charisma_a04",
		"rp_constitution_a04",
		"rp_intelligence_a04",
		"rp_precision_a04",
		"rp_precision_b01",
		"rp_charisma_b01",
		"rp_awareness_b01",
		"rp_precision_b02",
		"rp_charisma_b02",
		"rp_awareness_b02",
		"rp_precision_b03",
		"rp_precision_b04",
		"rp_charisma_b03",
		"rp_awareness_b03",
		"rp_ranged_novice",
		"rp_ranged_a01",
		"rp_armor_novice",
		"rp_armor_a01",
		"rp_composure_novice",
		"rp_composure_a01",
		"rp_investigation_novice",
		"rp_investigation_a01",
		"rp_persuasion_novice",
		"rp_persuasion_a01",
		"rp_piloting_novice",
		"rp_piloting_a01",
		"rp_ranged_a02",
		"rp_armor_a02",
		"rp_investigation_a02",
		"rp_persuasion_a02",
		"rp_ranged_a03",
		"rp_ranged_a04",
		"rp_investigation_a03",
		"rp_resolve_novice",
		"rp_investigation_a04",
		"rp_resolve_a01",
		"rp_resolve_a02",
		"rp_resolve_a03",
		"rp_athletics_novice",
		"rp_resolve_a04",
		"rp_persuasion_a03",
		"rp_ranged_b01",
		"rp_investigation_b01",
		"rp_athletics_a01",
		"rp_athletics_a02",
		"rp_athletics_a03",
		"rp_athletics_a04",
		"rp_maneuverability_novice",
		"rp_persuasion_a04",
		"rp_ranged_b02",
		"rp_piloting_a02",
		"rp_piloting_a03",
		"rp_piloting_a04",
		"rp_piloting_b01",
		"rp_piloting_b02",
		"rp_composure_a02",
		"rp_composure_a03",
		"rp_composure_a04",
		"rp_demolitions_novice",
		"rp_demolitions_a01",
		"rp_demolitions_a02",
		"rp_intimidation_novice",
		"rp_medicine_novice",
		"rp_medicine_a01",
		"rp_bluff_novice",
		"rp_bluff_a01",
		"rp_bluff_a02",
		"rp_bluff_a03",
		"rp_bluff_a04",
		"rp_bluff_b01",
		"rp_persuasion_b01",
		"rp_resolve_b01",
		"rp_medicine_a02",
		"rp_computers_novice",
		"rp_computers_a01",
		"rp_computers_a02",
		"rp_computers_a03",
		"rp_computers_a04",
		"rp_composure_b01",
		"rp_ranged_b03",
		"rp_defending_novice",
		"rp_strength_a01",
		"rp_utility_disguised",
		"rp_constitution_b01",
		"rp_athletics_b01",
		"rp_maneuverability_a01",
		"rp_maneuverability_a02",
		"rp_maneuverability_a03",
		"rp_maneuverability_a04",
		"rp_dexterity_a01",
		"rp_maneuverability_b01",
		"rp_stealth_novice",
		"rp_stealth_a01",
		"rp_stealth_a02",
		"rp_stealth_a03",
		"rp_maneuverability_b02",
		"rp_maneuverability_b03",
		"rp_composure_b02",
		"rp_ranged_b04",
		"rp_bluff_b02",
		"rp_persuasion_b02",
		"rp_demolitions_a03",
		"rp_bluff_b03",
		"rp_intimidation_a01",
		"rp_intimidation_a02",
		"rp_intimidation_a03",
		"rp_stealth_a04",
		"rp_slicing_novice",
		"rp_slicing_a01",
		"rp_slicing_a02",
		"rp_slicing_a03",
		"rp_slicing_a04",
		"rp_armor_a03",
		"rp_larceny_novice",
		"rp_larceny_a01",
		"rp_larceny_a02",
		"rp_larceny_a03",
		"rp_larceny_a04",
		"rp_medicine_a03",
		"rp_medicine_a04",
		"rp_medicine_b01",
		"rp_constitution_b02",
		"rp_athletics_b02",
		"rp_armor_a04",
		"rp_armor_b01",
		"rp_piloting_b03",
		"rp_resolve_b02",
	},
	customization = {
		{"/private/index_color_2", 20},
		{"/shared_owner/blend_skinny", 143},
		{"/shared_owner/blend_muscle", 148},
		{"/shared_owner/blend_fat", 0},
		{"/shared_owner/blend_nosedepth_1", 153},
		{"/shared_owner/blend_eyesize_0", 0},
		{"/shared_owner/blend_nosedepth_0", 0},
		{"/shared_owner/blend_noselength_1", 5},
		{"/shared_owner/blend_eyesize_1", 66},
		{"/shared_owner/blend_cheeks_0", 0},
		{"/shared_owner/blend_eyedirection_0", 0},
		{"/shared_owner/blend_noselength_0", 0},
		{"/shared_owner/blend_eyedirection_1", 255},
		{"/shared_owner/blend_nosewidth_0", 0},
		{"/shared_owner/blend_nosewidth_1", 14},
		{"/shared_owner/blend_cheeks_1", 10},
		{"/shared_owner/blend_jaw_1", 168},
		{"/shared_owner/blend_jaw_0", 0},
		{"/shared_owner/index_color_skin", 1},
		{"/shared_owner/blend_lipwidth_0", 0},
		{"/shared_owner/blend_lipwidth_1", 25},
		{"/shared_owner/blend_lipfullness_0", 0},
		{"/shared_owner/blend_lipfullness_1", 76},
		{"/shared_owner/blend_ears_0", 46},
		{"/shared_owner/blend_ears_1", 0},
		{"/shared_owner/blend_chinsize_1", 147},
		{"/shared_owner/blend_chinsize_0", 0},
		{"/private/index_color_3", 0},
		{"/private/index_style_eyebrow", 3},
		{"/private/index_color_facial_hair", 10},
		{"/shared_owner/blend_eyeshape_1", 0},
		{"/shared_owner/blend_eyeshape_0", 10},
		{"/private/index_style_beard", 0},
		{"/private/index_age", 0},
		{"/private/index_style_freckles", 1},
		{"height", 1.0132},
		{"hair_object", "object/tangible/hair/human/shared_hair_human_male_s02.iff","/private/index_color_1", 10, },
	},
}
-- Thank you for playing, Zevron. -Borrie BoBaka

