-- Account: client/profiles\creepio
-- Character: hal
-- Generated on: Sat Sep  9 16:22:12 2023
characterData = {
	firstName = "Hal",
	lastName = "Coryk",
	cash = 4338,
	bank = 0,
	experience = 1567,
	corruption = 0,
	faction = "empire",
	factionRank = "1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 2,
	lightsaberBuilder = -1,
	skills = {
		"rp_precision_novice",
		"species_human",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_utility_disguised",
		"rp_force_prog_novice",
		"rp_strength_a01",
		"rp_strength_a02",
		"rp_strength_a03",
		"rp_strength_a04",
		"rp_strength_b01",
		"rp_strength_b02",
		"rp_strength_b03",
		"rp_dexterity_a01",
		"rp_strength_b04",
		"rp_strength_master",
		"rp_mindfulness_a01",
		"rp_mindfulness_a02",
		"rp_mindfulness_a03",
		"rp_mindfulness_a04",
		"rp_mindfulness_b01",
		"rp_mindfulness_b02",
		"rp_mindfulness_b03",
		"rp_mindfulness_b04",
		"rp_mindfulness_master",
		"rp_dexterity_a02",
		"rp_dexterity_a03",
		"rp_dexterity_a04",
		"rp_dexterity_b01",
		"rp_constitution_a01",
		"rp_constitution_a02",
		"rp_constitution_a03",
		"rp_constitution_a04",
		"rp_constitution_b01",
		"rp_dexterity_b02",
		"rp_dexterity_b03",
		"rp_athletics_novice",
		"rp_athletics_a01",
		"rp_defending_novice",
		"rp_defending_a01",
		"rp_defending_a02",
		"rp_defending_a03",
		"rp_defending_a04",
		"rp_defending_b01",
		"rp_defending_b02",
		"rp_defending_b03",
		"rp_force_prog_rank_01",
		"rp_sense_novice",
		"rp_force_prog_rank_02",
		"rp_telekinesis_novice",
		"rp_telekinesis_a01",
		"rp_telekinesis_a02",
		"rp_sense_a01",
		"rp_sense_a02",
		"rp_alter_novice",
		"rp_alter_a01",
		"rp_alter_a02",
		"rp_lightsaber_novice",
		"rp_lightsaber_a01",
		"rp_control_novice",
		"rp_lightning_novice",
		"rp_control_a01",
		"rp_control_a02",
		"rp_lightning_a01",
		"rp_lightning_a02",
		"rp_inward_novice",
		"rp_inward_a01",
		"rp_inward_a02",
		"rp_force_prog_rank_03",
		"rp_sense_a03",
		"rp_telekinesis_a03",
		"rp_inward_a03",
		"rp_inward_a04",
		"rp_inward_b01",
		"rp_telekinesis_a04",
		"rp_telekinesis_b01",
		"rp_sense_a04",
		"rp_sense_b01",
		"rp_lightning_a03",
		"rp_lightning_a04",
		"rp_lightning_b01",
		"rp_lightsaber_a02",
		"rp_lightsaber_a03",
		"rp_lightsaber_a04",
		"rp_lightsaber_b01",
		"rp_lightsaber_b02",
		"rp_control_a03",
	},
	customization = {
		{"/private/index_color_2", 29},
		{"/shared_owner/blend_skinny", 76},
		{"/shared_owner/blend_muscle", 5},
		{"/shared_owner/blend_fat", 0},
		{"/shared_owner/blend_nosedepth_1", 10},
		{"/shared_owner/blend_eyesize_0", 0},
		{"/shared_owner/blend_nosedepth_0", 0},
		{"/shared_owner/blend_noselength_1", 204},
		{"/shared_owner/blend_eyesize_1", 0},
		{"/shared_owner/blend_cheeks_0", 0},
		{"/shared_owner/blend_eyedirection_0", 0},
		{"/shared_owner/blend_noselength_0", 0},
		{"/shared_owner/blend_eyedirection_1", 117},
		{"/shared_owner/blend_nosewidth_0", 0},
		{"/shared_owner/blend_nosewidth_1", 40},
		{"/shared_owner/blend_cheeks_1", 117},
		{"/shared_owner/blend_jaw_1", 0},
		{"/shared_owner/blend_jaw_0", 66},
		{"/shared_owner/index_color_skin", 10},
		{"/shared_owner/blend_lipwidth_0", 0},
		{"/shared_owner/blend_lipwidth_1", 61},
		{"/shared_owner/blend_lipfullness_0", 30},
		{"/shared_owner/blend_lipfullness_1", 0},
		{"/shared_owner/blend_ears_0", 87},
		{"/shared_owner/blend_ears_1", 0},
		{"/shared_owner/blend_chinsize_1", 0},
		{"/shared_owner/blend_chinsize_0", 76},
		{"/private/index_color_3", 0},
		{"/private/index_style_eyebrow", 3},
		{"/private/index_color_facial_hair", 0},
		{"/shared_owner/blend_eyeshape_1", 0},
		{"/shared_owner/blend_eyeshape_0", 255},
		{"/private/index_style_beard", 0},
		{"/private/index_age", 0},
		{"/private/index_style_freckles", 0},
		{"height", 1.0022},
		{"hair_object", "object/tangible/hair/human/shared_hair_human_male_s24.iff","/private/index_color_1", 15, },
	},
}
-- Thank you for playing, Hal. -Borrie BoBaka

