-- Account: whiskey
-- Character: alynn
-- Generated on: Sat Sep  9 16:12:43 2023
characterData = {
	firstName = "Alynn",
	lastName = "Sel'Boll",
	cash = 70,
	bank = 1000,
	experience = 2145,
	corruption = 0,
	faction = "liberty",
	factionRank = "1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 0,
	lightsaberBuilder = -1,
	skills = {
		"rp_precision_novice",
		"species_human",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_charisma_a01",
		"rp_charisma_a02",
		"rp_charisma_a03",
		"rp_charisma_a04",
		"rp_charisma_b01",
		"rp_charisma_b02",
		"rp_charisma_b03",
		"rp_intelligence_a01",
		"rp_intelligence_a02",
		"rp_intelligence_a03",
		"rp_intelligence_a04",
		"rp_mindfulness_a01",
		"rp_intelligence_b01",
		"rp_mindfulness_a02",
		"rp_awareness_a01",
		"rp_dexterity_a01",
		"rp_precision_a01",
		"rp_strength_a01",
		"rp_strength_a02",
		"rp_strength_a03",
		"rp_precision_a02",
		"rp_constitution_a01",
		"rp_constitution_a02",
		"rp_awareness_a02",
		"rp_charisma_b04",
		"rp_charisma_master",
		"rp_precision_a03",
		"rp_precision_a04",
		"rp_intelligence_b02",
		"rp_awareness_a03",
		"rp_persuasion_novice",
		"rp_persuasion_a01",
		"rp_persuasion_a02",
		"rp_ranged_novice",
		"rp_ranged_a01",
		"rp_persuasion_a03",
		"rp_persuasion_a04",
		"rp_piloting_novice",
		"rp_piloting_a01",
		"rp_composure_novice",
		"rp_composure_a01",
		"rp_composure_a02",
		"rp_bluff_novice",
		"rp_bluff_a01",
		"rp_bluff_a02",
		"rp_athletics_novice",
		"rp_athletics_a01",
		"rp_ranged_a02",
		"rp_composure_a03",
		"rp_composure_a04",
		"rp_piloting_a02",
		"rp_piloting_a03",
		"rp_ranged_a03",
		"rp_utility_disguised",
	},
	customization = {
		{"/private/index_color_2", 14},
		{"/shared_owner/blend_skinny", 5},
		{"/shared_owner/blend_muscle", 110},
		{"/shared_owner/blend_fat", 0},
		{"/shared_owner/blend_nosedepth_1", 0},
		{"/shared_owner/blend_eyesize_0", 0},
		{"/shared_owner/blend_nosedepth_0", 35},
		{"/shared_owner/blend_noselength_1", 97},
		{"/shared_owner/blend_eyesize_1", 102},
		{"/shared_owner/blend_cheeks_0", 0},
		{"/shared_owner/blend_eyedirection_0", 0},
		{"/shared_owner/blend_noselength_0", 0},
		{"/shared_owner/blend_eyedirection_1", 5},
		{"/shared_owner/blend_nosewidth_0", 107},
		{"/shared_owner/blend_nosewidth_1", 0},
		{"/shared_owner/blend_cheeks_1", 0},
		{"/shared_owner/blend_jaw_1", 0},
		{"/shared_owner/blend_jaw_0", 146},
		{"/shared_owner/index_color_skin", 8},
		{"/shared_owner/blend_lipwidth_0", 107},
		{"/shared_owner/blend_lipwidth_1", 0},
		{"/shared_owner/blend_lipfullness_0", 128},
		{"/shared_owner/blend_lipfullness_1", 0},
		{"/shared_owner/blend_ears_0", 133},
		{"/shared_owner/blend_ears_1", 0},
		{"/shared_owner/blend_chinsize_1", 25},
		{"/shared_owner/blend_chinsize_0", 0},
		{"/private/index_style_eyebrow", 5},
		{"/private/index_color_facial_hair", 7},
		{"/shared_owner/blend_eyeshape_1", 0},
		{"/shared_owner/blend_eyeshape_0", 71},
		{"/private/index_age", 1},
		{"/private/index_style_freckles", 2},
		{"/shared_owner/blend_flat_chest", 21},
		{"/private/index_color_eyeshadow", 55},
		{"/private/index_style_eyeshadow", 0},
		{"/private/index_color_lips", 3},
		{"height", 1.005},
		{"hair_object", "object/tangible/hair/human/shared_hair_human_female_s05.iff","/private/index_color_1", 9, },
	},
}
-- Thank you for playing, Alynn. -Borrie BoBaka

