-- Account: whiskey
-- Character: epha
-- Generated on: Sat Sep  9 16:12:21 2023
characterData = {
	firstName = "Epha",
	lastName = "Quess",
	cash = 0,
	bank = 11342,
	experience = 78469,
	corruption = -1,
	faction = "",
	factionRank = "-1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 4,
	lightsaberBuilder = 1,
	skills = {
		"rp_precision_novice",
		"species_human",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_force_prog_novice",
		"rp_mindfulness_a01",
		"rp_mindfulness_a02",
		"rp_charisma_a01",
		"rp_charisma_a02",
		"rp_charisma_a03",
		"rp_charisma_a04",
		"rp_awareness_a01",
		"rp_awareness_a02",
		"rp_constitution_a01",
		"rp_constitution_a02",
		"rp_constitution_a03",
		"rp_dexterity_a01",
		"rp_dexterity_a02",
		"rp_dexterity_a03",
		"rp_mindfulness_a03",
		"rp_mindfulness_a04",
		"rp_mindfulness_b01",
		"rp_dexterity_a04",
		"rp_mindfulness_b02",
		"rp_dexterity_b01",
		"rp_composure_novice",
		"rp_composure_a01",
		"rp_composure_a02",
		"rp_athletics_novice",
		"rp_melee_novice",
		"rp_persuasion_novice",
		"rp_bluff_novice",
		"rp_bluff_a01",
		"rp_survival_novice",
		"rp_resolve_novice",
		"rp_ranged_novice",
		"rp_defending_novice",
		"rp_ranged_a01",
		"rp_persuasion_a01",
		"rp_melee_a01",
		"rp_force_prog_rank_01",
		"rp_persuasion_a02",
		"rp_persuasion_a03",
		"rp_maneuverability_novice",
		"rp_sense_novice",
		"rp_force_prog_rank_02",
		"rp_lightsaber_novice",
		"rp_lightsaber_a01",
		"rp_resolve_a01",
		"rp_inward_novice",
		"rp_alter_novice",
		"rp_lightsaber_a02",
		"rp_maneuverability_a01",
		"rp_maneuverability_a02",
		"rp_investigation_novice",
		"rp_investigation_a01",
		"rp_persuasion_a04",
		"rp_maneuverability_a03",
		"rp_maneuverability_a04",
		"rp_inward_a01",
		"rp_inward_a02",
		"rp_sense_a01",
		"rp_sense_a02",
		"rp_athletics_a01",
		"rp_athletics_a02",
		"rp_maneuverability_b01",
		"rp_telekinesis_novice",
		"rp_telekinesis_a01",
		"rp_telekinesis_a02",
		"rp_telekinesis_a03",
		"rp_telekinesis_a04",
		"rp_alter_a01",
		"rp_alter_a02",
		"rp_alter_a03",
		"rp_inward_a03",
		"rp_force_prog_rank_03",
		"rp_inward_a04",
		"rp_athletics_a03",
		"rp_lightsaber_a03",
		"rp_lightsaber_a04",
		"rp_lightsaber_b01",
		"rp_composure_a03",
		"rp_composure_a04",
		"rp_resolve_a02",
		"rp_resolve_a03",
		"rp_resolve_a04",
		"rp_control_novice",
		"rp_control_a01",
		"rp_control_a02",
		"rp_alter_a04",
		"rp_inward_b01",
		"rp_inward_b02",
		"rp_alter_b01",
		"rp_alter_b02",
		"rp_control_a03",
		"rp_control_a04",
		"rp_control_b01",
		"rp_control_b02",
		"rp_mindfulness_b03",
		"rp_mindfulness_b04",
		"rp_mindfulness_master",
		"rp_constitution_a04",
		"rp_constitution_b01",
		"rp_constitution_b02",
		"rp_dexterity_b02",
		"rp_dexterity_b03",
		"rp_dexterity_b04",
		"rp_dexterity_master",
		"rp_control_b03",
		"rp_control_b04",
		"rp_control_master",
		"rp_alter_b03",
		"rp_alter_b04",
		"rp_force_prog_rank_04",
		"rp_inward_b03",
		"rp_utility_disguised",
		"rp_maneuverability_b02",
		"rp_athletics_a04",
		"rp_athletics_b01",
		"rp_lightsaber_b02",
		"rp_lightsaber_b03",
		"rp_training_jedi_novice",
		"rp_training_jedi_rank_01",
		"rp_training_jedi_rank_02",
		"rp_training_jedi_rank_03",
		"rp_training_jedi_rank_04",
		"rp_training_jedi_rank_05",
		"rp_lightsaber_b04",
		"social_language_wookiee_comprehend",
		"rp_training_jedi_rank_06",
	},
	customization = {
		{"/private/index_color_2", 21},
		{"/shared_owner/blend_skinny", 0},
		{"/shared_owner/blend_muscle", 53},
		{"/shared_owner/blend_fat", 5},
		{"/shared_owner/blend_nosedepth_1", 179},
		{"/shared_owner/blend_eyesize_0", 0},
		{"/shared_owner/blend_nosedepth_0", 0},
		{"/shared_owner/blend_noselength_1", 92},
		{"/shared_owner/blend_eyesize_1", 51},
		{"/shared_owner/blend_cheeks_0", 10},
		{"/shared_owner/blend_eyedirection_0", 0},
		{"/shared_owner/blend_noselength_0", 0},
		{"/shared_owner/blend_eyedirection_1", 30},
		{"/shared_owner/blend_nosewidth_0", 209},
		{"/shared_owner/blend_nosewidth_1", 0},
		{"/shared_owner/blend_cheeks_1", 0},
		{"/shared_owner/blend_jaw_1", 0},
		{"/shared_owner/blend_jaw_0", 56},
		{"/shared_owner/index_color_skin", 10},
		{"/shared_owner/blend_lipwidth_0", 112},
		{"/shared_owner/blend_lipwidth_1", 0},
		{"/shared_owner/blend_lipfullness_0", 209},
		{"/shared_owner/blend_lipfullness_1", 0},
		{"/shared_owner/blend_ears_0", 0},
		{"/shared_owner/blend_ears_1", 92},
		{"/shared_owner/blend_chinsize_1", 0},
		{"/shared_owner/blend_chinsize_0", 45},
		{"/private/index_style_eyebrow", 8},
		{"/private/index_color_facial_hair", 5},
		{"/shared_owner/blend_eyeshape_1", 0},
		{"/shared_owner/blend_eyeshape_0", 168},
		{"/private/index_age", 0},
		{"/private/index_style_freckles", 1},
		{"/shared_owner/blend_flat_chest", -115},
		{"/private/index_color_eyeshadow", 55},
		{"/private/index_style_eyeshadow", 1},
		{"/private/index_color_lips", 49},
		{"height", 0.94},
		{"hair_object", "object/tangible/hair/human/shared_hair_human_female_s24.iff","/private/index_color_2", 205, "/private/index_color_1", 5, },
	},
}
-- Thank you for playing, Epha. -Borrie BoBaka

