-- Account: whiskey
-- Character: liivani
-- Generated on: Sat Sep  9 18:32:39 2023
characterData = {
	firstName = "Liivani",
	lastName = "Sharr",
	cash = 475,
	bank = 500,
	experience = 67883,
	corruption = 0,
	faction = "",
	factionRank = "-1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 2,
	lightsaberBuilder = 1,
	skills = {
		"rp_precision_novice",
		"species_human",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_force_prog_novice",
		"rp_awareness_a01",
		"rp_awareness_a02",
		"rp_awareness_a03",
		"rp_awareness_a04",
		"rp_awareness_b01",
		"rp_awareness_b02",
		"rp_awareness_b03",
		"rp_awareness_b04",
		"rp_awareness_master",
		"rp_mindfulness_a01",
		"rp_mindfulness_a02",
		"rp_mindfulness_a03",
		"rp_mindfulness_a04",
		"rp_mindfulness_b01",
		"rp_mindfulness_b02",
		"rp_constitution_a01",
		"rp_constitution_a02",
		"rp_constitution_a03",
		"rp_dexterity_a01",
		"rp_dexterity_a02",
		"rp_dexterity_a03",
		"rp_intelligence_a01",
		"rp_intelligence_a02",
		"rp_maneuverability_novice",
		"rp_maneuverability_a01",
		"rp_athletics_novice",
		"rp_melee_novice",
		"rp_maneuverability_a02",
		"rp_maneuverability_a03",
		"rp_mechanics_novice",
		"rp_mechanics_a01",
		"rp_mechanics_a02",
		"rp_survival_novice",
		"rp_melee_a01",
		"rp_investigation_novice",
		"rp_investigation_a01",
		"rp_force_prog_rank_01",
		"rp_telekinesis_novice",
		"rp_force_prog_rank_02",
		"rp_telekinesis_a01",
		"rp_sense_novice",
		"rp_sense_a01",
		"rp_sense_a02",
		"rp_alter_novice",
		"rp_alter_a01",
		"rp_alter_a02",
		"social_language_wookiee_comprehend",
		"rp_athletics_a01",
		"rp_athletics_a02",
		"rp_athletics_a03",
		"rp_telekinesis_a02",
		"rp_mindfulness_b03",
		"rp_sense_a03",
		"rp_telekinesis_a03",
		"rp_telekinesis_a04",
		"rp_sense_a04",
		"rp_sense_b01",
		"rp_sense_b02",
		"rp_sense_b03",
		"rp_sense_b04",
		"rp_composure_novice",
		"rp_composure_a01",
		"rp_composure_a02",
		"rp_lightsaber_novice",
		"rp_inward_novice",
		"rp_science_novice",
		"rp_science_a01",
		"rp_utility_disguised",
		"rp_inward_a01",
		"rp_force_prog_rank_03",
		"rp_inward_a02",
		"rp_inward_a03",
		"rp_inward_a04",
		"rp_alter_a03",
		"rp_constitution_a04",
		"rp_dexterity_a04",
		"rp_dexterity_b01",
		"rp_dexterity_b02",
		"rp_dexterity_b03",
		"rp_mindfulness_b04",
		"rp_mindfulness_master",
		"rp_resolve_novice",
		"rp_resolve_a01",
		"rp_resolve_a02",
		"rp_resolve_a03",
		"rp_resolve_a04",
		"rp_sense_master",
	},
	customization = {
		{"/private/index_color_2", 4},
		{"/shared_owner/blend_skinny", 179},
		{"/shared_owner/blend_muscle", 12},
		{"/shared_owner/blend_fat", 0},
		{"/shared_owner/blend_nosedepth_1", 0},
		{"/shared_owner/blend_eyesize_0", 5},
		{"/shared_owner/blend_nosedepth_0", 143},
		{"/shared_owner/blend_noselength_1", 102},
		{"/shared_owner/blend_eyesize_1", 0},
		{"/shared_owner/blend_cheeks_0", 30},
		{"/shared_owner/blend_eyedirection_0", 5},
		{"/shared_owner/blend_noselength_0", 0},
		{"/shared_owner/blend_eyedirection_1", 0},
		{"/shared_owner/blend_nosewidth_0", 143},
		{"/shared_owner/blend_nosewidth_1", 0},
		{"/shared_owner/blend_cheeks_1", 0},
		{"/shared_owner/blend_jaw_1", 0},
		{"/shared_owner/blend_jaw_0", 71},
		{"/shared_owner/index_color_skin", 18},
		{"/shared_owner/blend_lipwidth_0", 168},
		{"/shared_owner/blend_lipwidth_1", 0},
		{"/shared_owner/blend_lipfullness_0", 0},
		{"/shared_owner/blend_lipfullness_1", 20},
		{"/shared_owner/blend_ears_0", 117},
		{"/shared_owner/blend_ears_1", 0},
		{"/shared_owner/blend_chinsize_1", 0},
		{"/shared_owner/blend_chinsize_0", 148},
		{"/private/index_style_eyebrow", 6},
		{"/private/index_color_facial_hair", 19},
		{"/shared_owner/blend_eyeshape_1", 0},
		{"/shared_owner/blend_eyeshape_0", 5},
		{"/private/index_age", 0},
		{"/private/index_style_freckles", 0},
		{"/shared_owner/blend_flat_chest", 115},
		{"/private/index_color_eyeshadow", 0},
		{"/private/index_style_eyeshadow", 0},
		{"/private/index_color_lips", 18},
		{"height", 0.9525},
		{"hair_object", "object/tangible/hair/human/shared_hair_human_female_s39.iff","/private/index_color_1", 19, },
	},
}
-- Thank you for playing, Liivani. -Borrie BoBaka

