-- Account: whiskey
-- Character: pli'rin'acirk
-- Generated on: Sat Sep  9 16:14:04 2023
characterData = {
	firstName = "Pli'rin'acirk",
	lastName = "",
	cash = 1020,
	bank = 0,
	experience = 1169,
	corruption = 0,
	faction = "",
	factionRank = "-1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 1,
	lightsaberBuilder = -1,
	skills = {
		"rp_precision_novice",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_force_prog_novice",
		"rp_mindfulness_a01",
		"rp_mindfulness_a02",
		"rp_mindfulness_a03",
		"rp_mindfulness_a04",
		"rp_mindfulness_b01",
		"rp_mindfulness_b02",
		"rp_mindfulness_b03",
		"rp_mindfulness_b04",
		"rp_mindfulness_master",
		"rp_constitution_a01",
		"rp_constitution_a02",
		"rp_constitution_a03",
		"rp_constitution_a04",
		"rp_constitution_b01",
		"rp_constitution_b02",
		"rp_dexterity_a01",
		"rp_dexterity_a02",
		"rp_dexterity_a03",
		"rp_dexterity_a04",
		"rp_dexterity_b01",
		"rp_dexterity_b02",
		"rp_dexterity_b03",
		"rp_dexterity_b04",
		"rp_dexterity_master",
		"rp_constitution_b03",
		"rp_constitution_b04",
		"rp_constitution_master",
		"rp_awareness_a01",
		"rp_awareness_a02",
		"rp_awareness_a03",
		"rp_maneuverability_novice",
		"rp_maneuverability_a01",
		"rp_maneuverability_a02",
		"rp_maneuverability_a03",
		"rp_maneuverability_a04",
		"rp_maneuverability_b01",
		"rp_maneuverability_b02",
		"rp_maneuverability_b03",
		"rp_maneuverability_b04",
		"rp_maneuverability_master",
		"rp_melee_novice",
		"rp_utility_disguised",
		"rp_ranged_novice",
		"rp_ranged_a01",
		"rp_ranged_a02",
	},
	customization = {
		{"/private/index_color_2", 5},
		{"/shared_owner/blend_skinny", 204},
		{"/shared_owner/blend_muscle", 128},
		{"/shared_owner/blend_fat", 0},
		{"/shared_owner/blend_nosedepth_1", 0},
		{"/shared_owner/blend_eyesize_0", 0},
		{"/shared_owner/blend_nosedepth_0", 71},
		{"/shared_owner/blend_noselength_1", 0},
		{"/shared_owner/blend_eyesize_1", 128},
		{"/shared_owner/blend_cheeks_0", 0},
		{"/shared_owner/blend_eyedirection_0", 0},
		{"/shared_owner/blend_noselength_0", 255},
		{"/shared_owner/blend_eyedirection_1", 30},
		{"/shared_owner/blend_nosewidth_0", 92},
		{"/shared_owner/blend_nosewidth_1", 0},
		{"/shared_owner/blend_cheeks_1", 5},
		{"/shared_owner/blend_jaw_1", 0},
		{"/shared_owner/blend_jaw_0", 128},
		{"/shared_owner/index_color_skin", 5},
		{"/shared_owner/blend_lipwidth_0", 117},
		{"/shared_owner/blend_lipwidth_1", 0},
		{"/shared_owner/blend_lipfullness_0", 0},
		{"/shared_owner/blend_lipfullness_1", 76},
		{"/shared_owner/blend_ears_0", 0},
		{"/shared_owner/blend_ears_1", 10},
		{"/shared_owner/blend_chinsize_1", 0},
		{"/shared_owner/blend_chinsize_0", 5},
		{"/shared_owner/blend_eyeshape_1", 46},
		{"/shared_owner/blend_eyeshape_0", 0},
		{"/private/index_age", 0},
		{"/shared_owner/blend_flat_chest", -28},
		{"height", 1.0025},
		{"hair_object", "object/tangible/hair/human/shared_hair_human_female_s01.iff","/private/index_color_2", 205, "/private/index_color_1", 99, },
	},
}
-- Thank you for playing, Pli'rin'acirk. -Borrie BoBaka

