-- Account: liltheris
-- Character: illi'arah
-- Generated on: Sun Sep 10 05:26:56 2023
characterData = {
	firstName = "Illi'arah",
	lastName = "Keima",
	cash = 11407,
	bank = 72864,
	experience = 4867,
	corruption = 0,
	faction = "bounty",
	factionRank = "1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 0,
	lightsaberBuilder = -1,
	skills = {
		"rp_precision_novice",
		"species_human",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_ranged_novice",
		"rp_precision_a01",
		"rp_precision_a02",
		"rp_awareness_a01",
		"rp_charisma_a01",
		"rp_strength_a01",
		"rp_constitution_a01",
		"rp_dexterity_a01",
		"rp_dexterity_a02",
		"rp_constitution_a02",
		"rp_precision_a03",
		"rp_precision_a04",
		"rp_precision_b01",
		"rp_precision_b02",
		"rp_precision_b03",
		"rp_precision_b04",
		"rp_precision_master",
		"rp_constitution_a03",
		"rp_awareness_a02",
		"rp_awareness_a03",
		"rp_awareness_a04",
		"rp_constitution_a04",
		"rp_dexterity_a03",
		"rp_awareness_b01",
		"rp_awareness_b02",
		"rp_awareness_b03",
		"rp_awareness_b04",
		"rp_athletics_novice",
		"rp_ranged_a01",
		"rp_ranged_a02",
		"rp_ranged_a03",
		"rp_ranged_a04",
		"rp_ranged_b01",
		"rp_ranged_b02",
		"rp_ranged_b03",
		"rp_ranged_b04",
		"rp_piloting_novice",
		"rp_investigation_novice",
		"rp_athletics_a01",
		"rp_slicing_novice",
		"rp_stealth_novice",
		"rp_armor_novice",
		"rp_medicine_novice",
		"rp_piloting_a01",
		"rp_piloting_a02",
		"rp_defending_novice",
		"rp_piloting_a03",
		"rp_armor_a01",
		"social_language_wookiee_comprehend",
		"rp_armor_a02",
		"rp_armor_a03",
		"rp_armor_a04",
		"rp_unarmed_novice",
		"rp_unarmed_a01",
		"rp_strength_a02",
		"rp_athletics_a02",
		"rp_athletics_a03",
		"rp_ranged_master",
		"rp_constitution_b01",
		"rp_constitution_b02",
		"rp_constitution_b03",
		"rp_constitution_b04",
		"rp_athletics_a04",
		"rp_athletics_b01",
		"rp_athletics_b02",
		"rp_piloting_a04",
		"rp_stealth_a01",
		"rp_athletics_b03",
		"rp_maneuverability_novice",
		"rp_maneuverability_a01",
		"rp_piloting_b01",
		"rp_piloting_b02",
		"rp_piloting_b03",
		"rp_maneuverability_a02",
		"rp_maneuverability_a03",
		"rp_defending_a01",
		"rp_defending_a02",
		"rp_defending_a03",
		"rp_defending_a04",
		"rp_defending_b01",
		"rp_defending_b02",
		"rp_defending_b03",
		"rp_unarmed_a02",
		"rp_intimidation_novice",
		"rp_intimidation_a01",
		"rp_intimidation_a02",
		"rp_melee_novice",
		"rp_melee_a01",
		"rp_defending_b04",
		"rp_strength_a03",
		"rp_utility_disguised",
		"rp_maneuverability_a04",
		"rp_maneuverability_b01",
		"rp_medicine_a01",
		"rp_medicine_a02",
		"rp_medicine_a03",
		"rp_medicine_a04",
		"rp_medicine_b01",
		"rp_unarmed_a03",
		"rp_throwing_novice",
		"rp_throwing_a01",
		"rp_throwing_a02",
		"rp_throwing_a03",
		"rp_athletics_b04",
		"rp_maneuverability_b02",
		"rp_maneuverability_b03",
		"rp_resolve_novice",
		"rp_resolve_a01",
		"rp_resolve_a02",
	},
	customization = {
		{"/private/index_color_2", 237},
		{"/shared_owner/blend_skinny", 76},
		{"/shared_owner/blend_muscle", 173},
		{"/shared_owner/blend_fat", 0},
		{"/shared_owner/blend_nosedepth_1", 0},
		{"/shared_owner/blend_eyesize_0", 0},
		{"/shared_owner/blend_nosedepth_0", 173},
		{"/shared_owner/blend_noselength_1", 117},
		{"/shared_owner/blend_eyesize_1", 132},
		{"/shared_owner/blend_cheeks_0", 107},
		{"/shared_owner/blend_eyedirection_0", 56},
		{"/shared_owner/blend_noselength_0", 0},
		{"/shared_owner/blend_eyedirection_1", 0},
		{"/shared_owner/blend_nosewidth_0", 225},
		{"/shared_owner/blend_nosewidth_1", 0},
		{"/shared_owner/blend_cheeks_1", 0},
		{"/shared_owner/blend_jaw_1", 0},
		{"/shared_owner/blend_jaw_0", 10},
		{"/shared_owner/index_color_skin", 255},
		{"/shared_owner/blend_lipwidth_0", 40},
		{"/shared_owner/blend_lipwidth_1", 0},
		{"/shared_owner/blend_lipfullness_0", 158},
		{"/shared_owner/blend_lipfullness_1", 0},
		{"/shared_owner/blend_ears_0", 0},
		{"/shared_owner/blend_ears_1", 5},
		{"/shared_owner/blend_chinsize_1", 0},
		{"/shared_owner/blend_chinsize_0", 61},
		{"/private/index_style_eyebrow", 5},
		{"/private/index_color_facial_hair", 15},
		{"/shared_owner/blend_eyeshape_1", 0},
		{"/shared_owner/blend_eyeshape_0", 56},
		{"/private/index_age", 0},
		{"/private/index_style_freckles", 4},
		{"/shared_owner/blend_flat_chest", -24},
		{"/private/index_color_eyeshadow", 55},
		{"/private/index_style_eyeshadow", 1},
		{"/private/index_color_lips", 19},
		{"height", 1.055},
		{"hair_object", "object/tangible/hair/human/shared_hair_human_female_s18.iff","/private/index_color_1", 127, },
	},
}
-- Thank you for playing, Illi'arah. -Borrie BoBaka

