-- Account: liltheris
-- Character: narestra
-- Generated on: Sat Sep  9 18:31:50 2023
characterData = {
	firstName = "Narestra",
	lastName = "",
	cash = 25121,
	bank = 462,
	experience = 13653,
	corruption = 25,
	faction = "",
	factionRank = "-1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 2,
	lightsaberBuilder = 1,
	skills = {
		"rp_precision_novice",
		"species_human",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_force_prog_novice",
		"rp_mindfulness_a01",
		"rp_mindfulness_a02",
		"rp_mindfulness_a03",
		"rp_mindfulness_a04",
		"rp_mindfulness_b01",
		"rp_mindfulness_b02",
		"rp_mindfulness_b03",
		"rp_mindfulness_b04",
		"rp_mindfulness_master",
		"rp_constitution_a01",
		"rp_constitution_a02",
		"rp_constitution_a03",
		"rp_constitution_a04",
		"rp_constitution_b01",
		"rp_awareness_a01",
		"rp_awareness_a02",
		"rp_constitution_b02",
		"rp_constitution_b03",
		"rp_constitution_b04",
		"rp_constitution_master",
		"rp_awareness_a03",
		"rp_athletics_novice",
		"rp_athletics_a01",
		"rp_athletics_a02",
		"rp_athletics_a03",
		"rp_athletics_a04",
		"rp_athletics_b01",
		"rp_athletics_b02",
		"rp_athletics_b03",
		"rp_athletics_b04",
		"rp_athletics_master",
		"rp_melee_novice",
		"rp_melee_a01",
		"rp_melee_a02",
		"rp_melee_a03",
		"rp_melee_a04",
		"rp_force_prog_rank_01",
		"rp_alter_novice",
		"rp_force_prog_rank_02",
		"rp_inward_novice",
		"rp_inward_a01",
		"rp_inward_a02",
		"rp_inward_a03",
		"rp_inward_a04",
		"rp_inward_b01",
		"rp_inward_b02",
		"rp_alter_a01",
		"rp_alter_a02",
		"rp_alter_a03",
		"rp_alter_a04",
		"rp_telekinesis_novice",
		"rp_lightsaber_novice",
		"rp_investigation_novice",
		"rp_investigation_a01",
		"rp_investigation_a02",
		"rp_investigation_a03",
		"rp_telekinesis_a01",
		"rp_telekinesis_a02",
		"rp_telekinesis_a03",
		"rp_melee_b01",
		"rp_lightsaber_a01",
		"rp_lightsaber_a02",
		"rp_lightsaber_a03",
		"rp_force_prog_rank_03",
		"rp_sense_novice",
		"rp_sense_a01",
		"rp_sense_a02",
		"rp_lightsaber_a04",
		"rp_lightsaber_b01",
		"rp_lightsaber_b02",
		"rp_lightsaber_b03",
		"rp_lightning_novice",
		"rp_lightning_a01",
		"rp_lightning_a02",
		"rp_lightning_a03",
		"rp_telekinesis_a04",
		"rp_telekinesis_b01",
		"rp_telekinesis_b02",
		"rp_telekinesis_b03",
		"rp_telekinesis_b04",
		"rp_telekinesis_master",
		"rp_control_novice",
		"rp_control_a01",
		"rp_control_a02",
		"rp_control_a03",
		"rp_control_a04",
		"rp_control_b01",
		"rp_defending_novice",
		"rp_alter_b01",
		"rp_force_prog_rank_04",
		"rp_alter_b02",
		"rp_sense_a03",
		"rp_lightning_a04",
		"rp_lightning_b01",
		"rp_lightning_b02",
		"rp_maneuverability_novice",
		"rp_melee_b02",
		"rp_survival_novice",
		"rp_survival_a01",
		"rp_survival_a02",
		"rp_survival_a03",
		"rp_lightsaber_b04",
		"rp_lightsaber_master",
		"rp_training_took_dk_novice",
		"rp_training_took_dk_rank_01",
		"rp_training_took_dk_rank_02",
		"rp_inward_b03",
		"rp_control_b02",
		"rp_control_b03",
		"rp_awareness_a04",
		"rp_sense_a04",
		"rp_unarmed_novice",
		"rp_unarmed_a01",
		"rp_unarmed_a02",
		"rp_piloting_novice",
		"rp_piloting_a01",
		"rp_piloting_a02",
		"rp_piloting_a03",
		"rp_alter_b03",
		"rp_alter_b04",
		"rp_alter_master",
		"rp_training_took_dk_rank_03",
		"rp_training_took_dk_rank_04",
		"rp_training_took_dk_rank_05",
		"rp_utility_disguised",
		"rp_dexterity_a01",
		"rp_dexterity_a02",
		"rp_dexterity_a03",
		"rp_dexterity_a04",
		"rp_dexterity_b01",
		"rp_dexterity_b02",
		"rp_dexterity_b03",
		"rp_dexterity_b04",
		"rp_dexterity_master",
		"rp_lightning_b03",
		"rp_lightning_b04",
		"rp_lightning_master",
		"rp_control_b04",
		"rp_maneuverability_a01",
		"rp_maneuverability_a02",
		"rp_maneuverability_a03",
		"rp_maneuverability_a04",
		"rp_control_master",
		"rp_sense_b01",
		"rp_sense_b02",
		"rp_sense_b03",
		"rp_stealth_novice",
		"rp_stealth_a01",
		"rp_stealth_a02",
		"rp_stealth_a03",
		"rp_unarmed_a03",
		"rp_strength_a01",
		"rp_resolve_novice",
		"rp_resolve_a01",
		"rp_resolve_a02",
		"rp_resolve_a03",
		"rp_inward_b04",
		"rp_melee_b03",
		"rp_melee_b04",
		"rp_inward_master",
		"rp_training_took_dk_rank_06",
		"rp_training_took_dk_rank_07",
		"rp_training_took_dk_rank_08",
		"rp_training_took_dk_rank_09",
		"rp_resolve_a04",
		"rp_resolve_b01",
		"rp_sense_b04",
		"rp_sense_master",
	},
	customization = {
		{"/private/index_color_2", 20},
		{"/shared_owner/blend_skinny", 86},
		{"/shared_owner/blend_muscle", 224},
		{"/shared_owner/blend_fat", 0},
		{"/shared_owner/blend_nosedepth_1", 0},
		{"/shared_owner/blend_eyesize_0", 0},
		{"/shared_owner/blend_nosedepth_0", 158},
		{"/shared_owner/blend_noselength_1", 107},
		{"/shared_owner/blend_eyesize_1", 51},
		{"/shared_owner/blend_cheeks_0", 153},
		{"/shared_owner/blend_eyedirection_0", 40},
		{"/shared_owner/blend_noselength_0", 0},
		{"/shared_owner/blend_eyedirection_1", 0},
		{"/shared_owner/blend_nosewidth_0", 214},
		{"/shared_owner/blend_nosewidth_1", 0},
		{"/shared_owner/blend_cheeks_1", 0},
		{"/shared_owner/blend_jaw_1", 0},
		{"/shared_owner/blend_jaw_0", 101},
		{"/shared_owner/index_color_skin", 12},
		{"/shared_owner/blend_lipwidth_0", 71},
		{"/shared_owner/blend_lipwidth_1", 0},
		{"/shared_owner/blend_lipfullness_0", 255},
		{"/shared_owner/blend_lipfullness_1", 0},
		{"/shared_owner/blend_ears_0", 50},
		{"/shared_owner/blend_ears_1", 0},
		{"/shared_owner/blend_chinsize_1", 0},
		{"/shared_owner/blend_chinsize_0", 25},
		{"/private/index_style_eyebrow", 1},
		{"/private/index_color_facial_hair", 99},
		{"/shared_owner/blend_eyeshape_1", 0},
		{"/shared_owner/blend_eyeshape_0", 132},
		{"/private/index_age", 0},
		{"/private/index_style_freckles", 0},
		{"/shared_owner/blend_flat_chest", -55},
		{"/private/index_color_eyeshadow", 55},
		{"/private/index_style_eyeshadow", 1},
		{"/private/index_color_lips", 30},
		{"height", 1.055},
		{"hair_object", "object/tangible/hair/human/shared_hair_human_female_s09.iff","/private/index_color_1", 10, },
	},
}
-- Thank you for playing, Narestra. -Borrie BoBaka

