-- Account: whiskey2
-- Character: yukarra
-- Generated on: Sat Sep  9 16:10:48 2023
characterData = {
	firstName = "Yukarra",
	lastName = "Deomer",
	cash = 632,
	bank = 13040,
	experience = 1077,
	corruption = 0,
	faction = "",
	factionRank = "-1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 0,
	lightsaberBuilder = -1,
	skills = {
		"rp_precision_novice",
		"species_human",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_intelligence_a01",
		"rp_intelligence_a02",
		"rp_intelligence_a03",
		"rp_intelligence_a04",
		"rp_intelligence_b01",
		"rp_intelligence_b02",
		"rp_intelligence_b03",
		"rp_intelligence_b04",
		"rp_intelligence_master",
		"rp_precision_a01",
		"rp_precision_a02",
		"rp_precision_a03",
		"rp_precision_a04",
		"rp_precision_b01",
		"rp_precision_b02",
		"rp_constitution_a01",
		"rp_precision_b03",
		"rp_constitution_a02",
		"rp_constitution_a03",
		"rp_constitution_a04",
		"rp_strength_a01",
		"rp_strength_a02",
		"rp_strength_a03",
		"rp_strength_a04",
		"rp_constitution_b01",
		"rp_constitution_b02",
		"rp_dexterity_a01",
		"rp_dexterity_a02",
		"rp_dexterity_a03",
		"rp_awareness_a01",
		"rp_science_novice",
		"rp_ranged_novice",
		"rp_ranged_a01",
		"rp_ranged_a02",
		"rp_ranged_a03",
		"rp_ranged_a04",
		"rp_ranged_b01",
		"rp_ranged_b02",
		"rp_ranged_b03",
		"rp_science_a01",
		"rp_science_a02",
		"rp_science_a03",
		"rp_science_a04",
		"rp_engineering_novice",
		"rp_engineering_a01",
		"rp_defending_novice",
		"rp_engineering_a02",
		"rp_engineering_a03",
		"rp_maneuverability_novice",
		"rp_maneuverability_a01",
		"rp_athletics_novice",
		"rp_athletics_a01",
		"rp_engineering_a04",
		"rp_athletics_a02",
		"rp_maneuverability_a02",
		"rp_unarmed_novice",
		"rp_unarmed_a01",
		"rp_unarmed_a02",
		"rp_unarmed_a03",
		"rp_unarmed_a04",
		"rp_maneuverability_a03",
		"rp_athletics_a03",
		"rp_throwing_novice",
		"rp_throwing_a01",
		"rp_engineering_b01",
		"rp_engineering_b02",
		"rp_throwing_a02",
		"rp_utility_disguised",
		"rp_demolitions_novice",
		"rp_demolitions_a01",
		"rp_demolitions_a02",
		"rp_demolitions_a03",
		"rp_demolitions_a04",
		"rp_throwing_a03",
		"rp_throwing_a04",
		"rp_athletics_a04",
	},
	customization = {
		{"/private/index_color_2", 0},
		{"/shared_owner/blend_skinny", 143},
		{"/shared_owner/blend_muscle", 151},
		{"/shared_owner/blend_fat", 0},
		{"/shared_owner/blend_nosedepth_1", 0},
		{"/shared_owner/blend_eyesize_0", 174},
		{"/shared_owner/blend_nosedepth_0", 204},
		{"/shared_owner/blend_noselength_1", 35},
		{"/shared_owner/blend_eyesize_1", 0},
		{"/shared_owner/blend_cheeks_0", 0},
		{"/shared_owner/blend_eyedirection_0", 0},
		{"/shared_owner/blend_noselength_0", 0},
		{"/shared_owner/blend_eyedirection_1", 25},
		{"/shared_owner/blend_nosewidth_0", 225},
		{"/shared_owner/blend_nosewidth_1", 0},
		{"/shared_owner/blend_cheeks_1", 81},
		{"/shared_owner/blend_jaw_1", 0},
		{"/shared_owner/blend_jaw_0", 25},
		{"/shared_owner/index_color_skin", 32},
		{"/shared_owner/blend_lipwidth_0", 117},
		{"/shared_owner/blend_lipwidth_1", 0},
		{"/shared_owner/blend_lipfullness_0", 46},
		{"/shared_owner/blend_lipfullness_1", 0},
		{"/shared_owner/blend_ears_0", 172},
		{"/shared_owner/blend_ears_1", 0},
		{"/shared_owner/blend_chinsize_1", 10},
		{"/shared_owner/blend_chinsize_0", 0},
		{"/private/index_style_eyebrow", 5},
		{"/private/index_color_facial_hair", 10},
		{"/shared_owner/blend_eyeshape_1", 255},
		{"/shared_owner/blend_eyeshape_0", 0},
		{"/private/index_age", 0},
		{"/private/index_style_freckles", 0},
		{"/shared_owner/blend_flat_chest", 53},
		{"/private/index_color_eyeshadow", 58},
		{"/private/index_style_eyeshadow", 1},
		{"/private/index_color_lips", 3},
		{"height", 0.9375},
		{"hair_object", "object/tangible/hair/human/shared_hair_human_female_s41.iff","/private/index_color_1", 10, },
	},
}
-- Thank you for playing, Yukarra. -Borrie BoBaka

