-- Account: fodder4death
-- Character: ragha
-- Generated on: Sun Sep 10 22:56:14 2023
characterData = {
	firstName = "Ragha",
	lastName = "",
	cash = 100,
	bank = 7000,
	experience = 18755,
	corruption = 0,
	faction = "adventure",
	factionRank = "1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 1,
	lightsaberBuilder = -1,
	skills = {
		"rp_precision_novice",
		"social_language_basic_comprehend",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_force_prog_novice",
		"rp_constitution_a01",
		"rp_constitution_a02",
		"rp_strength_a01",
		"rp_strength_a02",
		"rp_strength_a03",
		"rp_strength_a04",
		"rp_constitution_a03",
		"rp_constitution_a04",
		"rp_constitution_b01",
		"rp_constitution_b02",
		"rp_constitution_b03",
		"rp_constitution_b04",
		"rp_constitution_master",
		"rp_mindfulness_a01",
		"rp_mindfulness_a02",
		"rp_mindfulness_a03",
		"rp_mindfulness_a04",
		"rp_awareness_a01",
		"rp_awareness_a02",
		"rp_awareness_a03",
		"rp_awareness_a04",
		"rp_dexterity_a01",
		"rp_dexterity_a02",
		"rp_intelligence_a01",
		"rp_charisma_a01",
		"rp_charisma_a02",
		"rp_dexterity_a03",
		"rp_dexterity_a04",
		"rp_strength_b01",
		"rp_strength_b02",
		"rp_athletics_novice",
		"rp_athletics_a01",
		"rp_athletics_a02",
		"rp_athletics_a03",
		"rp_athletics_a04",
		"rp_athletics_b01",
		"rp_athletics_b02",
		"rp_athletics_b03",
		"rp_athletics_b04",
		"rp_athletics_master",
		"rp_melee_novice",
		"rp_melee_a01",
		"rp_melee_a02",
		"rp_unarmed_novice",
		"rp_unarmed_a01",
		"rp_unarmed_a02",
		"rp_melee_a03",
		"rp_investigation_novice",
		"rp_investigation_a01",
		"rp_investigation_a02",
		"rp_melee_a04",
		"rp_maneuverability_novice",
		"rp_maneuverability_a01",
		"rp_maneuverability_a02",
		"rp_maneuverability_a03",
		"rp_intimidation_novice",
		"rp_intimidation_a01",
		"rp_maneuverability_a04",
		"rp_melee_b01",
		"rp_melee_b02",
		"rp_defending_novice",
		"rp_utility_disguised",
		"rp_ranged_novice",
		"rp_intimidation_a02",
		"rp_intimidation_a03",
		"rp_intimidation_a04",
		"rp_defending_a01",
		"rp_defending_a02",
		"rp_defending_a03",
		"rp_defending_a04",
		"rp_defending_b01",
		"rp_defending_b02",
		"social_language_wookiee_comprehend",
	},
	customization = {
		{"/private/index_color_1", 0},
		{"height", 1},
	},
}
-- Thank you for playing, Ragha. -Borrie BoBaka

