-- Account: hellothere69
-- Character: unclebob
-- Generated on: Sun Sep 10 21:50:23 2023
characterData = {
	firstName = "UncleBob",
	lastName = "",
	cash = 103,
	bank = 24463,
	experience = 2351,
	corruption = 0,
	faction = "",
	factionRank = "-1",
	freeAttributes = 0,
	freeSkills = 0,
	jediState = 0,
	lightsaberBuilder = -1,
	skills = {
		"rp_precision_novice",
		"species_sullustan",
		"social_language_basic_comprehend",
		"social_language_basic_speak",
		"social_language_sullustan_comprehend",
		"social_language_sullustan_speak",
		"rp_strength_novice",
		"rp_dexterity_novice",
		"rp_awareness_novice",
		"rp_intelligence_novice",
		"rp_charisma_novice",
		"rp_constitution_novice",
		"rp_mindfulness_novice",
		"rp_bg_roleplayer",
		"rp_utility_disguised",
		"rp_charisma_a01",
		"rp_charisma_a02",
		"rp_charisma_a03",
		"rp_charisma_a04",
		"rp_charisma_b01",
		"rp_charisma_b02",
		"rp_charisma_b03",
		"rp_charisma_b04",
		"rp_composure_novice",
		"rp_composure_a01",
		"rp_ranged_novice",
		"rp_constitution_a01",
		"rp_constitution_a02",
		"rp_constitution_a03",
		"rp_precision_a01",
		"rp_precision_a02",
		"rp_constitution_a04",
		"rp_precision_a03",
		"rp_precision_a04",
		"rp_precision_b01",
		"rp_precision_b02",
		"rp_larceny_novice",
		"rp_larceny_a01",
		"rp_larceny_a02",
		"rp_larceny_a03",
		"rp_precision_b03",
		"rp_precision_b04",
		"rp_constitution_b01",
		"rp_constitution_b02",
		"rp_constitution_b03",
		"rp_constitution_b04",
		"rp_precision_master",
		"rp_constitution_master",
		"rp_charisma_master",
		"rp_awareness_a01",
		"rp_awareness_a02",
		"rp_awareness_a03",
		"rp_composure_a02",
		"rp_ranged_a01",
		"rp_ranged_a02",
		"rp_ranged_a03",
		"rp_composure_a03",
		"rp_persuasion_novice",
		"rp_persuasion_a01",
		"rp_persuasion_a02",
		"rp_persuasion_a03",
		"rp_armor_novice",
		"rp_armor_a01",
		"rp_armor_a02",
		"rp_bluff_novice",
		"rp_bluff_a01",
		"rp_bluff_a02",
		"rp_bluff_a03",
		"rp_bluff_a04",
	},
	customization = {
		{"/shared_owner/blend_skinny", 0},
		{"/shared_owner/blend_muscle", 135},
		{"/shared_owner/blend_fat", 255},
		{"/shared_owner/blend_eyesize_0", 255},
		{"/shared_owner/blend_noselength_1", 255},
		{"/shared_owner/blend_eyesize_1", 0},
		{"/shared_owner/blend_cheeks_0", 0},
		{"/shared_owner/blend_noselength_0", 0},
		{"/shared_owner/blend_nosewidth_0", 0},
		{"/shared_owner/blend_nosewidth_1", 255},
		{"/shared_owner/blend_cheeks_1", 255},
		{"/shared_owner/blend_jaw_1", 255},
		{"/shared_owner/blend_jaw_0", 0},
		{"/shared_owner/index_color_skin", 63},
		{"/shared_owner/blend_lipwidth_0", 0},
		{"/shared_owner/blend_lipwidth_1", 255},
		{"/shared_owner/blend_lipfullness_0", 0},
		{"/shared_owner/blend_lipfullness_1", 255},
		{"/shared_owner/blend_ears_0", 0},
		{"/shared_owner/blend_ears_1", 46},
		{"/shared_owner/blend_chinsize_1", 255},
		{"/shared_owner/blend_chinsize_0", 0},
		{"/shared_owner/blend_eyeshape_1", 71},
		{"/shared_owner/blend_eyeshape_0", 0},
		{"/private/index_age", 3},
		{"/shared_owner/blend_sensor_0", 0},
		{"/shared_owner/blend_sensor_1", 255},
		{"/shared_owner/blend_headsize_0", 0},
		{"/shared_owner/blend_headsize_1", 19},
		{"/private/index_color_eye", 16},
		{"/shared_owner/blend_ear_0", 255},
		{"/shared_owner/blend_ear_1", 0},
		{"/shared_owner/blend_brow_1", 227},
		{"/shared_owner/blend_brow_0", 0},
		{"/shared_owner/blend_chin_1", 255},
		{"/shared_owner/blend_chin_0", 0},
		{"/private/index_color_patterns", 17},
		{"/private/index_patterns", 0},
		{"height", 0.9928},
	},
}
-- Thank you for playing, UncleBob. -Borrie BoBaka

